version: "3.8"
services:

  db:
    image: mysql:latest
    container_name: ruakh_db
    restart: always
    volumes:
    - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ruakh_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: ruakh_mail_dev
    restart: always
    command: bin/maildev --web 80 --smtp 25 --hide-exetensions STARTTLS
    ports:
      - 8081:80
    networks:
      - dev

  apache:
    build: php
    container_name: ruakh_www
    ports:
    - 8741:80
    volumes:
    - ./php/vhosts:/etc/apache2/sites-enabled
    - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:


